apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilgramslanding-http
  labels:
    app: pilgramslanding-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pilgramslanding-http
  template:
    metadata:
      labels:
        app: pilgramslanding-http
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: pilgramslanding-http
        image: docker.mau.guru/pilgramslanding-http:v0.1.2
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: pilgramslanding-http-service
spec:
  selector:
    app: pilgramslanding-http
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pilgramslanding-http-cert
  namespace: default
spec:
  secretName: pilgramslanding-http-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - pilgramslanding.life
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pilgramslanding-http-ingress-secure
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`pilgramslanding.life`)
    kind: Rule
    services:
    - name: pilgramslanding-http-service
      port: 80
  tls:
    secretName: pilgramslanding-http-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pilgramslanding-http-ingress-insecure
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pilgramslanding.life`)
      kind: Rule
      services:
        - name: pilgramslanding-http-service
          port: 80
      middlewares:
        - name: default-https-redirect@kubernetescrd

