apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-mau-guru
  namespace: default
spec:
  secretName: test-mau-guru-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - test.mau.guru

