apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-mau-guru
  namespace: default
spec:
  secretName: argo-mau-guru-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - argo.mau.guru
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-ingress-secure
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`argo.mau.guru`)
    kind: Rule
    services:
    - name: argocd-server
      port: 443
  tls:
    secretName: argo-mau-guru-tls
