apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-mau-guru
  namespace: default
spec:
  secretName: argo-mau-guru-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - argo.mau.guru
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
spec:
  tls:
    - secretName: argo-mau-guru-tls
      hosts:
        - argo.mau.guru
  rules:
    - host: argo.mau.guru
      http:
        paths:
          - path: /
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
            pathType: ImplementationSpecific
